app:
    resource: "@AppBundle/Controller/"
    type:     annotation

redirect_homepage:
  path: / # What the user type in the explorer
  defaults: 
    _controller: FrameworkBundle:Redirect:redirect
    route: homepage_article
    permanent: true
